### ISSUE TITLE
no type named ‘value_type’

### ISSUE THREAD

**Issue by sytham** [maciekgajewski/c-excercises#5]
Whatever I try, I get

```
$ make
g++ -o list_test -g -Wall -std=c++11 list_test.cc
In file included from /usr/include/c++/4.8/bits/stl_algobase.h:67:0,
                 from /usr/include/c++/4.8/vector:60,
                 from list_test.cc:7:
/usr/include/c++/4.8/bits/stl_iterator.h: In instantiation of ‘class std::front_insert_iterator<MyLinkedList<int> >’:
list_test.cc:56:57:   required from ‘void Populate(MyLinkedList&) [with MyLinkedList = MyLinkedList<int>]’
list_test.cc:88:12:   required from here
/usr/include/c++/4.8/bits/stl_iterator.h:526:7: error: no type named ‘value_type’ in ‘class MyLinkedList<int>’
       operator=(const typename _Container::value_type& __value)
       ^
```

where list_test.cc:56 is

`std::copy(vec.begin(), vec.end(), std::front_inserter(l));`

i.e. the exact same line as in Populate() in Maciek's list_test.cc. I call the method as

```
MyLinkedList<int> l;
Populate(l);
```

As method signatures, I've tried

```
template<typename MyLinkedList>
void Populate(MyLinkedList& l)
```

```
template<typename T>
void Populate(T& l)
```

( and then calling as `Populate<MyLinkedList>(l)` or `Populate<MyLinkedList<int>>(l)` ). Also tried
`void Populate(MyLinkedList& l)`
`void Populate(MyLinkedList<int>& l)`
, i.e. non-template method. In all cases, I got the same error.

I have also tried

```
template<typename MyLinkedList<int>>
void Populate(MyLinkedList<int>& l)
```

but then I got

```
$ make
g++ -o list_test -g -Wall -std=c++11 list_test.cc
list_test.cc:47:19: error: expected nested-name-specifier
 template<typename MyLinkedList<int>>
                   ^
```

**Comment by sytham** [comment]
Solved it. [This](http://en.cppreference.com/w/cpp/iterator/front_insert_iterator) seemed to indicate that front_insert_iterator requires a "member type" called value_type. The std::list doc and [Container description](http://en.cppreference.com/w/cpp/concept/Container) described a similar thing. I had no idea what that was supposed to mean, but [this](http://stackoverflow.com/questions/14037392/how-are-member-types-implemented) provided a hint. So in my class definition:

```
template<typename T>
class MyLinkedList
{
public:
    typedef T value_type; 
```

I added the value_type typedef. This compiles and runs. I don't understand this, aside from it being a requirement for complying with the Container concept. But don't understand what difference it makes.

**Comment by maciekgajewski** [comment]
Look at the source code of front_instert_iterator, you will se how the nested type is used.

For instance:

```
    front_insert_iterator&
    operator=(typename _Container::value_type&& __value)
    {
        container->push_front(std::move(__value));
        return *this;
    }
```

**Comment by sytham** [comment]
Cool, where / how can I view the source code?
